# Data General Processing

In [ ]:
df_master = pd.read_csv('output_path')

In [3]:
df_master["gender"].value_counts()

gender
F    64272
M    54077
U       36
Name: count, dtype: int64

# 1. General filter - Age, triage_acuity

In [4]:
print('Before filtering for "age" >= 18 : master dataset size = ', len(df_master))
df_master = df_master[df_master['age'] >= 18]
print('After filtering for "age" >= 18 : master dataset size = ', len(df_master))

Before filtering for "age" >= 18 : master dataset size =  118385
After filtering for "age" >= 18 : master dataset size =  118385

In [5]:
print('Before filtering for non-null "triage_acuity" >= 18 : master dataset size = ', len(df_master))
df_master = df_master[df_master['triage_acuity'].notnull()]
print('After filtering for non-null "triage_acuity" >= 18 : master dataset size = ', len(df_master))

Before filtering for non-null "triage_acuity" >= 18 : master dataset size =  118385
After filtering for non-null "triage_acuity" >= 18 : master dataset size =  117858

# 2. Outlier Detection

In [6]:
vitals_valid_range = {
    'temperature': {'outlier_low': 14.2, 'valid_low': 26, 'valid_high': 45, 'outlier_high':47},
    'heartrate': {'outlier_low': 0, 'valid_low': 0, 'valid_high': 350, 'outlier_high':390},
    'resprate': {'outlier_low': 0, 'valid_low': 0, 'valid_high': 300, 'outlier_high':330},
    'o2sat': {'outlier_low': 0, 'valid_low': 0, 'valid_high': 100, 'outlier_high':150},
    'sbp': {'outlier_low': 0, 'valid_low': 0, 'valid_high': 375, 'outlier_high':375},
    'dbp': {'outlier_low': 0, 'valid_low': 0, 'valid_high': 375, 'outlier_high':375},
    'pain': {'outlier_low': 0, 'valid_low': 0, 'valid_high': 10, 'outlier_high':10},
    'acuity': {'outlier_low': 1, 'valid_low': 1, 'valid_high': 5, 'outlier_high':5},
}

In [7]:
display_outliers_count(df_master, vitals_valid_range)

,variable,< outlier_low,"[outlier_low, valid_low)","[valid_low, valid_high]","(valid_high, outlier_high]",> outlier_high
0,triage_temperature,0,1,108425,0,0
1,triage_heartrate,0,0,117716,0,0
2,triage_resprate,0,0,117685,0,0
3,triage_o2sat,0,0,117654,0,0
4,triage_sbp,0,0,117307,0,0
5,triage_dbp,0,0,117278,0,0
6,triage_acuity,0,0,117858,0,0

In [8]:
df_master = remove_outliers(df_master, vitals_valid_range)

In [9]:
pd.set_option('display.max_columns', None)
df_master.head()

,subject_id,stay_id,age,gender,race,ethnicity,intime,outtime,in_year,edregtime,edouttime,admittime,dischtime,intime_icu,outtime_icu,ed_los,ed_los_hours,next_ed_visit_time,next_ed_visit_time_diff,next_ed_visit_time_diff_days,time_to_icu_transfer_hours,triage_temperature,triage_heartrate,triage_resprate,triage_o2sat,triage_sbp,triage_dbp,triage_acuity,triage_MAP,CC,chiefcom_chest_pain,chiefcom_abdominal_pain,chiefcom_headache,chiefcom_shortness_of_breath,chiefcom_back_pain,chiefcom_cough,chiefcom_nausea_vomiting,chiefcom_fever_chills,chiefcom_syncope,chiefcom_dizziness,n_ed_30d,n_ed_90d,n_ed_365d,n_hosp_30d,n_hosp_90d,n_hosp_365d,n_icu_30d,n_icu_90d,n_icu_365d,n_med,n_medrecon,cci_MI,cci_CHF,cci_PVD,cci_Stroke,cci_Dementia,cci_Pulmonary,cci_Rheumatic,cci_PUD,cci_Liver1,cci_DM1,cci_DM2,cci_Paralysis,cci_Renal,cci_Cancer1,cci_Liver2,cci_Cancer2,cci_HIV,eci_HIV,eci_Alcohol,eci_BloodLoss,eci_Arrhythmia,eci_Pulmonary,eci_Coagulopathy,eci_CHF,eci_Anemia,eci_Depression,eci_DM2,eci_DM1,eci_Drugs,eci_FluidsLytes,eci_HTN2,eci_HTN1,eci_Hypothyroid,eci_Liver,eci_Lymphoma,eci_Tumor2,eci_Obesity,eci_NeuroOther,eci_Paralysis,eci_PUD,eci_PVD,eci_Psychoses,eci_PHTN,eci_Renal,eci_Rheumatic,eci_Tumor1,eci_Valvular,eci_WeightLoss,score_REMS,score_CART,score_NEWS,score_NEWS2,score_MEWS,score_CCI,ALBUMIN,ALKALINE PHOSPHATASE,ALT (SGPT),ANION GAP,AST (SGOT),BASOPHIL % (AUTO DIFF),"BILIRUBIN, TOTAL",BLOOD UREA NITROGEN (BUN),BLOOD: URINE (UA),"BNP, NT-PRO",Basophil Absolute (Combined),CHLORIDE,CO2,CREATININE,Calcium (Combined),EOSINOPHIL % (AUTO DIFF),Eosinophil Absolute (Combined),GLOBULIN,GLUCOSE,GLUCOSE: URINE (UA),HCT & Hemoglobin (Combined),HEMATOCRIT (HCT),HIGH SENSITIVITY TROPONIN,IMMATURE GRANULOCYTE % (AUTODIFF) WAM,"IMMATURE GRANULOCYTE, ABSOLUTE (AUTO DIFF) WAM",INFLUENZA A,INFLUENZA B,INR,KETONE: URINE (UA),LEUKOCYTE ESTERASE: URINE (UA),LIPASE,LYMPHOCYTE % (AUTO DIFF),Lymphocyte Absolute (Combined),MAGNESIUM,MEAN CORPUSCULAR VOLUME (MCV),MONOCYTE % (AUTO DIFF),Monocyte Absolute (Combined),NEUTROPHIL % (AUTO DIFF),"NEUTROPHIL, ABSOLUTE (AUTO DIFF)",NITRITE: URINE (UA),NRBC (Combined),PART. THROMBOPLASTIN TIME,"PCO2, Venous (Combined)",PH: URINE (UA),PLATELET COUNT (PLT),"PO2, Venous (Combined)","POC: BHCG, ISTAT QUANTITATIVE","POC: HCG, ISTAT QUALITATIVE","POC:BASE EXCESS, ISTAT",POC:GLUCOSE BY METER,"POC:HCO3 (V), ISTAT","POC:LACTATE, ISTAT","POC:O2 SATURATION, ISTAT VENOUS","POC:TCO2 (V), ISTAT","PROTEIN, TOTAL",PROTEIN: URINE (UA),PROTHROMBIN TIME,Potassium (Combined),RED BLOOD CELLS (RBC),RED CELL DISTRIBUTION WIDTH (RDW),RSV,SARS-COV-2 RNA,SPECIFIC GRAVITY: URINE (UA),Sodium (Combined),TROPONIN I,WHITE BLOOD CELLS (WBC),eGFR (Combined),"pH, Venous (Combined)",outcome_sepsis,outcome_copd_exac,outcome_acs_mi,outcome_stroke,outcome_ards,outcome_aki,outcome_pe,outcome_pneumonia_bacterial,outcome_pneumonia_viral,outcome_pneumonia_all,outcome_asthma_acute_exac,outcome_ahf,outcome_hospitalization,outcome_critical,outcome_discharge,outcome_ed_revisit_72h,outcome_ed_revisit_168h,outcome_ed_revisit_720h,outcome_sepsis_3d,outcome_copd_exac_3d,outcome_acs_mi_3d,outcome_stroke_3d,outcome_ards_3d,outcome_aki_3d,outcome_pe_3d,outcome_pneumonia_bacterial_3d,outcome_pneumonia_viral_3d,outcome_pneumonia_all_3d,outcome_asthma_acute_exac_3d,outcome_ahf_3d,outcome_icu_transfer_12h,outcome_sepsis_3d_new,outcome_copd_exac_3d_new,outcome_acs_mi_3d_new,outcome_stroke_3d_new,outcome_ards_3d_new,outcome_aki_3d_new,outcome_pe_3d_new,outcome_pneumonia_bacterial_3d_new,outcome_pneumonia_viral_3d_new,outcome_pneumonia_all_3d_new,outcome_asthma_acute_exac_3d_new,outcome_ahf_3d_new
0,98880961,98874959,82,F,White,Non-Hispanic/Non-Latino,2083-03-02 07:36:59,2083-03-02 13:44:59,2283,2083-03-02 07:36:59,2083-03-02 12:29:59,2083-03-02 12:29:59,2083-03-03 12:29:59,NaN,NaN,0.3,6.13,NaN,NaN,NaN,NaN,36.2,81.0,18.0,96.0,122.0,86.0,3.0,98.000000,FALL,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,9,0,0,1,5,3.4,139.0,28.0,9.0,38.0,8.0,2.0,17.0,34.0,NaN,7.0,108.0,23.0,84.000000,9.250000,3.8,32.0,4.7,109.000000,34.0,17.500000,21.133333,NaN,5.0,4.0,NaN,NaN,NaN,34.0,NaN,NaN,13.1,1.11,NaN,70.033333,8.6,73.00,73.2,6.23,2.0,0.0,NaN,NaN,6.0,410.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.1,34.0,NaN,4.500000,3.016667,22.2,NaN,NaN,1.0200,140.0,17.0,8.1,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,99121566,99354408,59,F,Other,Non-Hispanic/Non-Latino,2039-08-22 01:13:51,2039-08-22 10:45:51,2239,2039-08-22 01:16:51,2039-08-22 07:20:51,2039-08-22 07:20:51,2039-08-29 07:20:51,NaN,NaN,0.4,9.53,2040-03-10 18:13:51,4841.0,201.7,NaN,36.8,98.0,14.0,98.0,103.0,66.0,2.0,78.333333,"ALTERED MENTAL STATUS,SHORTNESS OF BREATH",0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,12,0,1,1,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,1,1,0,0,0,0,1,1,0,0,1,1,0,0,1,0,0,0,1,0,0,0,0,0,1,0,3,4,2,2,0,8,3.8,290.0,27.0,15.0,35.0,NaN,2.5,44.0,NaN,56.0,NaN,90.0,25.0,1.210000,9.600000,NaN,38.0,4.1,184.000000,34.0,19.700000,35.800000,NaN,NaN,NaN,NaN,NaN,1.3,34.0,34.0,NaN,NaN,NaN,2.5,95.200000,NaN,76.00,NaN,NaN,1.0,NaN,27.5,43.45,5.0,203.000000,37.5,NaN,NaN,7.5,NaN,26.35,2.520,69.5,28.0,7.9,34.0,15.5,5.000000,3.760000,18.4,NaN,1.0,1.0100,130.0,17.0,14.6,52.000000,7.380,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,99121566,99121037,63,F,Other,Non-Hispanic/Non-Latino,2040-03-11 03:06:51,2040-03-11 13:37:51,2240,2040-03-11 03:43:51,2040-03-11 08:31:51,NaN,NaN,2040-03-11 08:31:51,2040-03-27 08:31:51,0.4,10.52,NaN,NaN,NaN,5.42,37.2,96.0,18.0,98.0,91.0,61.0,3.0,71.000000,"ABNORMAL LAB,GENERAL WEAKNESS",0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,6,14,0,1,1,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,1,1,0,0,0,0,1,1,0,0,1,1,0,0,1,0,0,0,1,0,0,0,0,0,1,0,3,4,3,3,2,9,3.2,776.0,20.0,14.0,75.0,8.0,1.5,60.0,34.0,191.0,7.0,104.0,19.0,1.826667,9.398333,7.2,63.0,4.4,138.666667,34.0,25.033333,37.000000,NaN,1.2,11.0,1.0,1.0,1.3,34.0,34.0,NaN,10.1,89.00,NaN,102.500000,11.6,1.02,69.1,6.09,1.0,0.0,27.9,37.80,5.0,185.000000,41.5,NaN,NaN,2.5,161.0,22.55,1.095,75.0,23.5,7.6,34.0,15.7,5.966667,3.610000,17.5,1.0,1.0,1.0115,137.0,NaN,8.8,31.833333,7.385,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0
3,99608739,99327434,90,F,White,Non-Hispanic/Non-Latino,2096-08-31 16:43:05,2096-08-31 21:06:05,2296,2096-08-31 17:56:05,2096-08-31 20:56:05,NaN,NaN,NaN,NaN,0.2,4.38,2097-06-07 00:43:05,6704.0,279.3,NaN,NaN,69.0,16.0,98.0,107.0,42.0,3.0,63.666667,POSSIBLE DVT,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,10,13,1,1,1,5,4.4,56.0,14.0,12.0,32.0,7.0,1.0,19.0,NaN,NaN,5.0,101.0,23.0,78.000000,8.950000,1.8,14.0,2.2,80.000000,NaN,26.200000,41.100000,NaN,3.0,2.0,NaN,NaN,1.0,NaN,NaN,NaN,39.8,3.05,NaN,92.800000,11.7,90.00,45.7,3.51,NaN,0.0,27.7,NaN,NaN,219.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.6,NaN,12.7,3.600000,4.430000,13.2,NaN,NaN,NaN,136.0,NaN,7.7,73.000000,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,99608739,99502864,89,F,White,Non-Hispanic/Non-Latino,2097-06-07 05:08:05,2097-06-07 09:35:05,2297,2097-06-07 05:59:05,2097-06-07 08:55:05,NaN,NaN,NaN,NaN,0.2,4.45,NaN,NaN,NaN,NaN,36.4,65.0,17.0,98.0,103.0,57.0,3.0,72.333333,URINARY RETENTION,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,8,9,1,1,1,5,4.2,64.0,15.0,9.0,21.0,6.0,1.3,13.0,NaN,NaN,4.0,98.0,24.0,71.000000,8.800000,2.4,17.0,2.4,94.000000,34.0,26.600000,38.800000,NaN,4.0,3.0,NaN,NaN,NaN,34.0,34.0,NaN,33.8,2.35,NaN,88.800000,13.5,94.00,49.3,3.42,1.0,0.0,NaN,NaN,6.0,229.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.6,34.0,NaN,3.800000,4.370000,12.2,NaN,1.0,1.0090,131.0,NaN,7.0,81.000000,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

# 3. Dataset Split (train:0.8, test: 0.2, use seed to fix)

In [10]:
df_train=df_master.sample(frac=0.8,random_state=10) 
df_test=df_master.drop(df_train.index)

In [11]:
print('Training dataset size = ', len(df_train))
print('Testing dataset size = ', len(df_test))

Training dataset size =  94286
Testing dataset size =  23572

In [12]:
df_train.head()

,subject_id,stay_id,age,gender,race,ethnicity,intime,outtime,in_year,edregtime,edouttime,admittime,dischtime,intime_icu,outtime_icu,ed_los,ed_los_hours,next_ed_visit_time,next_ed_visit_time_diff,next_ed_visit_time_diff_days,time_to_icu_transfer_hours,triage_temperature,triage_heartrate,triage_resprate,triage_o2sat,triage_sbp,triage_dbp,triage_acuity,triage_MAP,CC,chiefcom_chest_pain,chiefcom_abdominal_pain,chiefcom_headache,chiefcom_shortness_of_breath,chiefcom_back_pain,chiefcom_cough,chiefcom_nausea_vomiting,chiefcom_fever_chills,chiefcom_syncope,chiefcom_dizziness,n_ed_30d,n_ed_90d,n_ed_365d,n_hosp_30d,n_hosp_90d,n_hosp_365d,n_icu_30d,n_icu_90d,n_icu_365d,n_med,n_medrecon,cci_MI,cci_CHF,cci_PVD,cci_Stroke,cci_Dementia,cci_Pulmonary,cci_Rheumatic,cci_PUD,cci_Liver1,cci_DM1,cci_DM2,cci_Paralysis,cci_Renal,cci_Cancer1,cci_Liver2,cci_Cancer2,cci_HIV,eci_HIV,eci_Alcohol,eci_BloodLoss,eci_Arrhythmia,eci_Pulmonary,eci_Coagulopathy,eci_CHF,eci_Anemia,eci_Depression,eci_DM2,eci_DM1,eci_Drugs,eci_FluidsLytes,eci_HTN2,eci_HTN1,eci_Hypothyroid,eci_Liver,eci_Lymphoma,eci_Tumor2,eci_Obesity,eci_NeuroOther,eci_Paralysis,eci_PUD,eci_PVD,eci_Psychoses,eci_PHTN,eci_Renal,eci_Rheumatic,eci_Tumor1,eci_Valvular,eci_WeightLoss,score_REMS,score_CART,score_NEWS,score_NEWS2,score_MEWS,score_CCI,ALBUMIN,ALKALINE PHOSPHATASE,ALT (SGPT),ANION GAP,AST (SGOT),BASOPHIL % (AUTO DIFF),"BILIRUBIN, TOTAL",BLOOD UREA NITROGEN (BUN),BLOOD: URINE (UA),"BNP, NT-PRO",Basophil Absolute (Combined),CHLORIDE,CO2,CREATININE,Calcium (Combined),EOSINOPHIL % (AUTO DIFF),Eosinophil Absolute (Combined),GLOBULIN,GLUCOSE,GLUCOSE: URINE (UA),HCT & Hemoglobin (Combined),HEMATOCRIT (HCT),HIGH SENSITIVITY TROPONIN,IMMATURE GRANULOCYTE % (AUTODIFF) WAM,"IMMATURE GRANULOCYTE, ABSOLUTE (AUTO DIFF) WAM",INFLUENZA A,INFLUENZA B,INR,KETONE: URINE (UA),LEUKOCYTE ESTERASE: URINE (UA),LIPASE,LYMPHOCYTE % (AUTO DIFF),Lymphocyte Absolute (Combined),MAGNESIUM,MEAN CORPUSCULAR VOLUME (MCV),MONOCYTE % (AUTO DIFF),Monocyte Absolute (Combined),NEUTROPHIL % (AUTO DIFF),"NEUTROPHIL, ABSOLUTE (AUTO DIFF)",NITRITE: URINE (UA),NRBC (Combined),PART. THROMBOPLASTIN TIME,"PCO2, Venous (Combined)",PH: URINE (UA),PLATELET COUNT (PLT),"PO2, Venous (Combined)","POC: BHCG, ISTAT QUANTITATIVE","POC: HCG, ISTAT QUALITATIVE","POC:BASE EXCESS, ISTAT",POC:GLUCOSE BY METER,"POC:HCO3 (V), ISTAT","POC:LACTATE, ISTAT","POC:O2 SATURATION, ISTAT VENOUS","POC:TCO2 (V), ISTAT","PROTEIN, TOTAL",PROTEIN: URINE (UA),PROTHROMBIN TIME,Potassium (Combined),RED BLOOD CELLS (RBC),RED CELL DISTRIBUTION WIDTH (RDW),RSV,SARS-COV-2 RNA,SPECIFIC GRAVITY: URINE (UA),Sodium (Combined),TROPONIN I,WHITE BLOOD CELLS (WBC),eGFR (Combined),"pH, Venous (Combined)",outcome_sepsis,outcome_copd_exac,outcome_acs_mi,outcome_stroke,outcome_ards,outcome_aki,outcome_pe,outcome_pneumonia_bacterial,outcome_pneumonia_viral,outcome_pneumonia_all,outcome_asthma_acute_exac,outcome_ahf,outcome_hospitalization,outcome_critical,outcome_discharge,outcome_ed_revisit_72h,outcome_ed_revisit_168h,outcome_ed_revisit_720h,outcome_sepsis_3d,outcome_copd_exac_3d,outcome_acs_mi_3d,outcome_stroke_3d,outcome_ards_3d,outcome_aki_3d,outcome_pe_3d,outcome_pneumonia_bacterial_3d,outcome_pneumonia_viral_3d,outcome_pneumonia_all_3d,outcome_asthma_acute_exac_3d,outcome_ahf_3d,outcome_icu_transfer_12h,outcome_sepsis_3d_new,outcome_copd_exac_3d_new,outcome_acs_mi_3d_new,outcome_stroke_3d_new,outcome_ards_3d_new,outcome_aki_3d_new,outcome_pe_3d_new,outcome_pneumonia_bacterial_3d_new,outcome_pneumonia_viral_3d_new,outcome_pneumonia_all_3d_new,outcome_asthma_acute_exac_3d_new,outcome_ahf_3d_new
10533,99295423,99012728,64,F,White,Non-Hispanic/Non-Latino,2070-11-12 19:15:58,2070-11-13 00:11:58,2270,2070-11-12 20:58:58,2070-11-12 23:42:58,NaN,NaN,NaN,NaN,0.2,4.93,2070-12-27 13:15:58,1074.0,44.8,NaN,36.7,70.0,20.0,100.0,164.0,87.0,3.0,112.666667,SKIN PROBLEM,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,4,0,0,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
108328,99311142,99618094,29,M,Other,Non-Hispanic/Non-Latino,2054-11-01 09:17:33,2054-11-01 11:49:33,2254,2054-11-01 09:57:33,2054-11-01 11:12:33,NaN,NaN,NaN,NaN,0.1,2.53,NaN,NaN,NaN,NaN,36.5,76.0,16.0,100.0,158.0,87.0,4.0,110.666667,EPISTAXIS,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,1,0,NaN,NaN,NaN,NaN,NaN,1.1,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,2.0,19.0,NaN,NaN,NaN,25.666667,45.60,NaN,6.0,6.0,NaN,NaN,1.0,NaN,NaN,NaN,40.20,3.89,NaN,89.90,9.7,94.0,46.40,4.48,NaN,0.0,32.7,NaN,NaN,257.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.2,NaN,5.07,13.2,NaN,NaN,NaN,NaN,NaN,9.70,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
101584,99510007,99518815,66,F,Asian,Non-Hispanic/Non-Latino,2053-06-05 19:23:20,2053-06-06 01:52:20,2253,2053-06-05 20:54:20,2053-06-06 01:26:20,NaN,NaN,NaN,NaN,0.3,6.48,2053-10-17 05:23:20,3202.0,133.4,NaN,36.7,90.0,18.0,100.0,138.0,64.0,3.0,88.666667,BACK PAIN,0,0,0,0,1,0,0,0,0,0,1,2,2,0,0,0,0,0,0,3,5,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,5,4,0,0,1,10,4.0,105.0,26.0,10.0,26.0,NaN,2.0,16.0,34.0,NaN,NaN,103.0,25.0,45.00,9.400000,NaN,17.0,3.2,93.0,34.0,21.566667,25.10,NaN,NaN,NaN,NaN,NaN,NaN,34.0,34.0,489.0,NaN,7.63,NaN,88.40,NaN,43.0,NaN,NaN,1.0,NaN,NaN,NaN,6.0,374.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.2,34.0,NaN,4.1,2.84,20.2,NaN,1.0,1.016,138.0,17.0,4.70,113.5,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
84728,99313513,99758667,34,M,Asian,Non-Hispanic/Non-Latino,2027-10-03 07:15:41,2027-10-03 10:20:41,2227,2027-10-03 07:53:41,2027-10-03 10:07:41,NaN,NaN,NaN,NaN,0.1,3.08,NaN,NaN,NaN,NaN,36.9,90.0,16.0,97.0,129.0,87.0,3.0,101.000000,MELENA,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,4.5,73.0,22.0,11.0,26.0,7.0,6.0,6.0,34.0,NaN,6.0,103.0,26.0,93.00,8.900000,10.6,86.0,3.0,101.0,34.0,26.766667,44.70,NaN,9.0,7.0,NaN,NaN,NaN,34.0,34.0,45.0,13.80,1.12,NaN,88.20,11.6,94.0,62.40,5.06,1.0,0.0,NaN,NaN,7.0,276.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.5,34.0,NaN,3.3,5.07,12.7,NaN,NaN,1.001,140.0,NaN,8.10,116.5,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
27939,99499209,99680681,82,F,Other,Non-Hispanic/Non-Latino,2062-03-13 15:07:07,2062-03-14 03:28:07,2262,2062-03-13 15:27:07,2062-03-13 21:51:07,NaN,NaN,NaN,NaN,0.5,12.35,2062-05-15 15:07:07,1512.0,63.0,NaN,36.5,60.0,15.0,97.0,125.0,68.0,3.0,87.000000,"EMESIS,BREATHING PROBLEM",0,0,0,1,0,0,1,0,0,0,1,1,1,1,1,1,0,0,0,2,12,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,8,9,0,0,1,10,3.7,272.0,22.0,16.0,36.0,5.0,1.6,65.0,34.0,NaN,3.5,93.0,25.0,2.02,7.436667,1.5,10.5,4.2,205.0,34.0,24.333333,40.85,NaN,6.0,4.0,1.0,1.0,1.3,34.0,34.0,74.0,13.45,94.50,NaN,90.35,12.7,89.5,71.25,5.02,1.0,0.0,NaN,39.3,6.0,118.0,59.0,NaN,NaN,3.5,169.0,27.5,2.6,91.5,28.5,7.9,34.0,16.3,4.7,4.52,16.3,1.0,1.0,1.010,134.0,17.0,7.05,24.0,7.455,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

4. Missing Value imputation

In [13]:
df_missing_stats = df_train.isnull().sum().to_frame().T
df_missing_stats.loc[1] = df_missing_stats.loc[0] / len(df_train)
df_missing_stats.index = ['no. of missing values', 'percentage of missing values']
df_missing_stats

,subject_id,stay_id,age,gender,race,ethnicity,intime,outtime,in_year,edregtime,edouttime,admittime,dischtime,intime_icu,outtime_icu,ed_los,ed_los_hours,next_ed_visit_time,next_ed_visit_time_diff,next_ed_visit_time_diff_days,time_to_icu_transfer_hours,triage_temperature,triage_heartrate,triage_resprate,triage_o2sat,triage_sbp,triage_dbp,triage_acuity,triage_MAP,CC,chiefcom_chest_pain,chiefcom_abdominal_pain,chiefcom_headache,chiefcom_shortness_of_breath,chiefcom_back_pain,chiefcom_cough,chiefcom_nausea_vomiting,chiefcom_fever_chills,chiefcom_syncope,chiefcom_dizziness,n_ed_30d,n_ed_90d,n_ed_365d,n_hosp_30d,n_hosp_90d,n_hosp_365d,n_icu_30d,n_icu_90d,n_icu_365d,n_med,n_medrecon,cci_MI,cci_CHF,cci_PVD,cci_Stroke,cci_Dementia,cci_Pulmonary,cci_Rheumatic,cci_PUD,cci_Liver1,cci_DM1,cci_DM2,cci_Paralysis,cci_Renal,cci_Cancer1,cci_Liver2,cci_Cancer2,cci_HIV,eci_HIV,eci_Alcohol,eci_BloodLoss,eci_Arrhythmia,eci_Pulmonary,eci_Coagulopathy,eci_CHF,eci_Anemia,eci_Depression,eci_DM2,eci_DM1,eci_Drugs,eci_FluidsLytes,eci_HTN2,eci_HTN1,eci_Hypothyroid,eci_Liver,eci_Lymphoma,eci_Tumor2,eci_Obesity,eci_NeuroOther,eci_Paralysis,eci_PUD,eci_PVD,eci_Psychoses,eci_PHTN,eci_Renal,eci_Rheumatic,eci_Tumor1,eci_Valvular,eci_WeightLoss,score_REMS,score_CART,score_NEWS,score_NEWS2,score_MEWS,score_CCI,ALBUMIN,ALKALINE PHOSPHATASE,ALT (SGPT),ANION GAP,AST (SGOT),BASOPHIL % (AUTO DIFF),"BILIRUBIN, TOTAL",BLOOD UREA NITROGEN (BUN),BLOOD: URINE (UA),"BNP, NT-PRO",Basophil Absolute (Combined),CHLORIDE,CO2,CREATININE,Calcium (Combined),EOSINOPHIL % (AUTO DIFF),Eosinophil Absolute (Combined),GLOBULIN,GLUCOSE,GLUCOSE: URINE (UA),HCT & Hemoglobin (Combined),HEMATOCRIT (HCT),HIGH SENSITIVITY TROPONIN,IMMATURE GRANULOCYTE % (AUTODIFF) WAM,"IMMATURE GRANULOCYTE, ABSOLUTE (AUTO DIFF) WAM",INFLUENZA A,INFLUENZA B,INR,KETONE: URINE (UA),LEUKOCYTE ESTERASE: URINE (UA),LIPASE,LYMPHOCYTE % (AUTO DIFF),Lymphocyte Absolute (Combined),MAGNESIUM,MEAN CORPUSCULAR VOLUME (MCV),MONOCYTE % (AUTO DIFF),Monocyte Absolute (Combined),NEUTROPHIL % (AUTO DIFF),"NEUTROPHIL, ABSOLUTE (AUTO DIFF)",NITRITE: URINE (UA),NRBC (Combined),PART. THROMBOPLASTIN TIME,"PCO2, Venous (Combined)",PH: URINE (UA),PLATELET COUNT (PLT),"PO2, Venous (Combined)","POC: BHCG, ISTAT QUANTITATIVE","POC: HCG, ISTAT QUALITATIVE","POC:BASE EXCESS, ISTAT",POC:GLUCOSE BY METER,"POC:HCO3 (V), ISTAT","POC:LACTATE, ISTAT","POC:O2 SATURATION, ISTAT VENOUS","POC:TCO2 (V), ISTAT","PROTEIN, TOTAL",PROTEIN: URINE (UA),PROTHROMBIN TIME,Potassium (Combined),RED BLOOD CELLS (RBC),RED CELL DISTRIBUTION WIDTH (RDW),RSV,SARS-COV-2 RNA,SPECIFIC GRAVITY: URINE (UA),Sodium (Combined),TROPONIN I,WHITE BLOOD CELLS (WBC),eGFR (Combined),"pH, Venous (Combined)",outcome_sepsis,outcome_copd_exac,outcome_acs_mi,outcome_stroke,outcome_ards,outcome_aki,outcome_pe,outcome_pneumonia_bacterial,outcome_pneumonia_viral,outcome_pneumonia_all,outcome_asthma_acute_exac,outcome_ahf,outcome_hospitalization,outcome_critical,outcome_discharge,outcome_ed_revisit_72h,outcome_ed_revisit_168h,outcome_ed_revisit_720h,outcome_sepsis_3d,outcome_copd_exac_3d,outcome_acs_mi_3d,outcome_stroke_3d,outcome_ards_3d,outcome_aki_3d,outcome_pe_3d,outcome_pneumonia_bacterial_3d,outcome_pneumonia_viral_3d,outcome_pneumonia_all_3d,outcome_asthma_acute_exac_3d,outcome_ahf_3d,outcome_icu_transfer_12h,outcome_sepsis_3d_new,outcome_copd_exac_3d_new,outcome_acs_mi_3d_new,outcome_stroke_3d_new,outcome_ards_3d_new,outcome_aki_3d_new,outcome_pe_3d_new,outcome_pneumonia_bacterial_3d_new,outcome_pneumonia_viral_3d_new,outcome_pneumonia_all_3d_new,outcome_asthma_acute_exac_3d_new,outcome_ahf_3d_new
no. of missing values,0.0,0.0,0.0,0.0,301.000000,301.000000,0.0,179.000000,0.0,0.0,410.000000,71016.000000,71046.000000,92140.000000,92142.000000,179.000000,179.000000,47485.000000,47485.000000,47485.000000,92140.000000,7522.000000,119.000000,147.000000,174.000000,461.000000,483.000000,0.0,483.000000,22.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19799.000000,19803.000000,19818.00000,18907.000000,19810.000000,24860.000000,19801.00000,18827.00000,74635.000000,84301.000000,23399.00000,18896.000000,18896.000000,18892.000000,18869.000000,24860.000000,22454.000000,19854.000000,18828.00000,66198.000000,18149.000000,18197.000000,84735.000000,24925.000000,24925.000000,72532.000000,72532.000000,69816.00000,66372.000000,69989.000000,75496.000000,24860.000000,20259.000000,83172.000000,18256.000000,24860.000000,20415.000000,24860.000000,24860.000000,62922.000000,23648.000000,71230.000000,70008.000000,62768.000000,18225.000000,69988.000000,80907.000000,81263.000000,70113.00000,86655.000000,70185.000000,70098.000000,70199.000000,70185.000000,19805.000000,70425.00000,69816.00000,18812.000000,18243.000000,18315.000000,75889.000000,33007.000000,62754.000000,18748.000000,67049.000000,18171.000000,19460.000000,70008.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
percentage of missing values,0.0,0.0,0.0,0.0,0.003192,0.003192,0.0,0.001898,0.0,0.0,0.004348,0.753198,0.753516,0.977239,0.977261,0.001898,0.001898,0.503627,0.503627,0.503627,0.977239,0.079779,0.001262,0.001559,0.001845,0.004889,0.005123,0.0,0.005123,0.000233,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.209989,0.210031,0.21019,0.200528,0.210105,0.263666,0.21001,0.19968,0.791581,0.894099,0.24817,0.200412,0.200412,0.200369,0.200125,0.263666,0.238148,0.210572,0.19969,0.702098,0.192489,0.192998,0.898702,0.264355,0.264355,0.769276,0.769276,0.74047,0.703943,0.742305,0.800713,0.263666,0.214868,0.882125,0.193624,0.263666,0.216522,0.263666,0.263666,0.667353,0.250811,0.755467,0.742507,0.665719,0.193295,0.742295,0.858102,0.861878,0.74362,0.919065,0.744384,0.743461,0.744533,0.744384,0.210052,0.74693,0.74047,0.199521,0.193486,0.194249,0.804881,0.350073,0.665571,0.198842,0.711124,0.192722,0.206393,0.742507,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
# Vitals that need imputation
vitals_cols = [col for col in df_master.columns if len(col.split('_')) > 1 and 
                                                   col.split('_')[1] in vitals_valid_range and
                                                   col.split('_')[1] != 'acuity']
vitals_cols

['triage_temperature',
 'triage_heartrate',
 'triage_resprate',
 'triage_o2sat',
 'triage_sbp',
 'triage_dbp']

In [15]:
imputer = SimpleImputer(strategy='median')
df_train[vitals_cols] = imputer.fit_transform(df_train[vitals_cols])
df_test[vitals_cols] = imputer.transform(df_test[vitals_cols])

In [16]:
# Labs that need imputation

lab_columns = [
    'ALBUMIN', 'ALKALINE PHOSPHATASE', 'ALT (SGPT)', 'ANION GAP', 'AST (SGOT)', 
    'BASOPHIL % (AUTO DIFF)', 'BILIRUBIN, TOTAL', 'BLOOD UREA NITROGEN (BUN)', 
    'BLOOD: URINE (UA)', 'BNP, NT-PRO', 'Basophil Absolute (Combined)', 'CHLORIDE', 
    'CO2', 'CREATININE', 'Calcium (Combined)', 'EOSINOPHIL % (AUTO DIFF)', 
    'Eosinophil Absolute (Combined)', 'GLOBULIN', 'GLUCOSE', 'GLUCOSE: URINE (UA)', 
    'HCT & Hemoglobin (Combined)', 'HEMATOCRIT (HCT)', 'HIGH SENSITIVITY TROPONIN', 
    'IMMATURE GRANULOCYTE % (AUTODIFF) WAM', 'IMMATURE GRANULOCYTE, ABSOLUTE (AUTO DIFF) WAM', 
    'INFLUENZA A', 'INFLUENZA B', 'INR', 'KETONE: URINE (UA)', 'LEUKOCYTE ESTERASE: URINE (UA)', 
    'LIPASE', 'LYMPHOCYTE % (AUTO DIFF)', 'Lymphocyte Absolute (Combined)', 'MAGNESIUM', 
    'MEAN CORPUSCULAR VOLUME (MCV)', 'MONOCYTE % (AUTO DIFF)', 'Monocyte Absolute (Combined)', 
    'NEUTROPHIL % (AUTO DIFF)', 'NEUTROPHIL, ABSOLUTE (AUTO DIFF)', 'NITRITE: URINE (UA)', 
    'NRBC (Combined)', 'PART. THROMBOPLASTIN TIME', 'PCO2, Venous (Combined)', 
    'PH: URINE (UA)', 'PLATELET COUNT (PLT)', 'PO2, Venous (Combined)', 
    'POC: BHCG, ISTAT QUANTITATIVE', 'POC: HCG, ISTAT QUALITATIVE', 'POC:BASE EXCESS, ISTAT', 
    'POC:GLUCOSE BY METER', 'POC:HCO3 (V), ISTAT', 'POC:LACTATE, ISTAT', 
    'POC:O2 SATURATION, ISTAT VENOUS', 'POC:TCO2 (V), ISTAT', 'PROTEIN, TOTAL', 
    'PROTEIN: URINE (UA)', 'PROTHROMBIN TIME', 'Potassium (Combined)', 
    'RED BLOOD CELLS (RBC)', 'RED CELL DISTRIBUTION WIDTH (RDW)', 'RSV', 'SARS-COV-2 RNA', 
    'SPECIFIC GRAVITY: URINE (UA)', 'Sodium (Combined)', 'TROPONIN I', 
    'WHITE BLOOD CELLS (WBC)', 'eGFR (Combined)', 'pH, Venous (Combined)'
]

existing_lab_columns = [col for col in lab_columns if col in df_master.columns]
print(f"Found {len(existing_lab_columns)} out of {len(lab_columns)} lab columns in the dataset")

df_labs = df_master[existing_lab_columns]

Found 68 out of 68 lab columns in the dataset

In [17]:
# Print all lab testing with their percentage of missing values
print("=== All Lab Tests with Missing Value Percentages ===")
print(f"{'Lab Test Name':<50} {'Missing %':<10} {'Missing Count':<15} {'Available Count'}")

lab_missing_summary = []

for col in existing_lab_columns:
    missing_count = df_train[col].isnull().sum()
    available_count = len(df_train) - missing_count
    missing_pct = missing_count / len(df_train) * 100
    
    lab_missing_summary.append({
        'Lab': col,
        'Missing_Pct': missing_pct,
        'Missing_Count': missing_count,
        'Available_Count': available_count
    })
    
    print(f"{col:<50} {missing_pct:>7.1f}%   {missing_count:>10}     {available_count:>10}")

lab_missing_summary.sort(key=lambda x: x['Missing_Pct'], reverse=True)

print("\n" + "=" * 95)
print("=== Labs Sorted by Missing Percentage (Highest to Lowest) ===")
print(f"{'Rank':<5} {'Lab Test Name':<50} {'Missing %':<10} {'Available Data'}")
print("-" * 95)

for i, lab in enumerate(lab_missing_summary, 1):
    print(f"{i:<5} {lab['Lab']:<50} {lab['Missing_Pct']:>7.1f}%   {lab['Available_Count']:>10} patients")

print(f"\n=== Summary Statistics ===")
print(f"Total lab columns analyzed: {len(existing_lab_columns)}")
print(f"Training dataset size: {len(df_train)}")

ranges = [
    (100, 100, "100% missing"),
    (95, 99.9, "95-99% missing"), 
    (90, 94.9, "90-95% missing"),
    (80, 89.9, "80-90% missing"),
    (50, 79.9, "50-80% missing"),
    (0, 49.9, "0-50% missing")
]

for min_pct, max_pct, label in ranges:
    count = len([lab for lab in lab_missing_summary if min_pct <= lab['Missing_Pct'] <= max_pct])
    if count > 0:
        print(f"{label}: {count} columns")

=== All Lab Tests with Missing Value Percentages ===
Lab Test Name                                      Missing %  Missing Count   Available Count
ALBUMIN                                               21.0%        19799          74487
ALKALINE PHOSPHATASE                                  21.0%        19803          74483
ALT (SGPT)                                            21.0%        19818          74468
ANION GAP                                             20.1%        18907          75379
AST (SGOT)                                            21.0%        19810          74476
BASOPHIL % (AUTO DIFF)                                26.4%        24860          69426
BILIRUBIN, TOTAL                                      21.0%        19801          74485
BLOOD UREA NITROGEN (BUN)                             20.0%        18827          75459
BLOOD: URINE (UA)                                     79.2%        74635          19651
BNP, NT-PRO                                           89.4%        84301           9985
Basophil Absolute (Combined)                          24.8%        23399          70887
CHLORIDE                                              20.0%        18896          75390
CO2                                                   20.0%        18896          75390
CREATININE                                            20.0%        18892          75394
Calcium (Combined)                                    20.0%        18869          75417
EOSINOPHIL % (AUTO DIFF)                              26.4%        24860          69426
Eosinophil Absolute (Combined)                        23.8%        22454          71832
GLOBULIN                                              21.1%        19854          74432
GLUCOSE                                               20.0%        18828          75458
GLUCOSE: URINE (UA)                                   70.2%        66198          28088
HCT & Hemoglobin (Combined)                           19.2%        18149          76137
HEMATOCRIT (HCT)                                      19.3%        18197          76089
HIGH SENSITIVITY TROPONIN                             89.9%        84735           9551
IMMATURE GRANULOCYTE % (AUTODIFF) WAM                 26.4%        24925          69361
IMMATURE GRANULOCYTE, ABSOLUTE (AUTO DIFF) WAM        26.4%        24925          69361
INFLUENZA A                                           76.9%        72532          21754
INFLUENZA B                                           76.9%        72532          21754
INR                                                   74.0%        69816          24470
KETONE: URINE (UA)                                    70.4%        66372          27914
LEUKOCYTE ESTERASE: URINE (UA)                        74.2%        69989          24297
LIPASE                                                80.1%        75496          18790
LYMPHOCYTE % (AUTO DIFF)                              26.4%        24860          69426
Lymphocyte Absolute (Combined)                        21.5%        20259          74027
MAGNESIUM                                             88.2%        83172          11114
MEAN CORPUSCULAR VOLUME (MCV)                         19.4%        18256          76030
MONOCYTE % (AUTO DIFF)                                26.4%        24860          69426
Monocyte Absolute (Combined)                          21.7%        20415          73871
NEUTROPHIL % (AUTO DIFF)                              26.4%        24860          69426
NEUTROPHIL, ABSOLUTE (AUTO DIFF)                      26.4%        24860          69426
NITRITE: URINE (UA)                                   66.7%        62922          31364
NRBC (Combined)                                       25.1%        23648          70638
PART. THROMBOPLASTIN TIME                             75.5%        71230          23056
PCO2, Venous (Combined)                               74.3%        70008          24278
PH: URINE (UA)                                        66.6%        62768          31518
PLATELET COUNT (PLT)                                  19.3%        18225          76061
PO2, Venous (Combined)                                74.2%        69988          24298
POC: BHCG, ISTAT QUANTITATIVE                         85.8%        80907          13379
POC: HCG, ISTAT QUALITATIVE                           86.2%        81263          13023
POC:BASE EXCESS, ISTAT                                74.4%        70113          24173
POC:GLUCOSE BY METER                                  91.9%        86655           7631
POC:HCO3 (V), ISTAT                                   74.4%        70185          24101
POC:LACTATE, ISTAT                                    74.3%        70098          24188
POC:O2 SATURATION, ISTAT VENOUS                       74.5%        70199          24087
POC:TCO2 (V), ISTAT                                   74.4%        70185          24101
PROTEIN, TOTAL                                        21.0%        19805          74481
PROTEIN: URINE (UA)                                   74.7%        70425          23861
PROTHROMBIN TIME                                      74.0%        69816          24470
Potassium (Combined)                                  20.0%        18812          75474
RED BLOOD CELLS (RBC)                                 19.3%        18243          76043
RED CELL DISTRIBUTION WIDTH (RDW)                     19.4%        18315          75971
RSV                                                   80.5%        75889          18397
SARS-COV-2 RNA                                        35.0%        33007          61279
SPECIFIC GRAVITY: URINE (UA)                          66.6%        62754          31532
Sodium (Combined)                                     19.9%        18748          75538
TROPONIN I                                            71.1%        67049          27237
WHITE BLOOD CELLS (WBC)                               19.3%        18171          76115
eGFR (Combined)                                       20.6%        19460          74826
pH, Venous (Combined)                                 74.3%        70008          24278

===============================================================================================
=== Labs Sorted by Missing Percentage (Highest to Lowest) ===
Rank  Lab Test Name                                      Missing %  Available Data
-----------------------------------------------------------------------------------------------
1     POC:GLUCOSE BY METER                                  91.9%         7631 patients
2     HIGH SENSITIVITY TROPONIN                             89.9%         9551 patients
3     BNP, NT-PRO                                           89.4%         9985 patients
4     MAGNESIUM                                             88.2%        11114 patients
5     POC: HCG, ISTAT QUALITATIVE                           86.2%        13023 patients
6     POC: BHCG, ISTAT QUANTITATIVE                         85.8%        13379 patients
7     RSV                                                   80.5%        18397 patients
8     LIPASE                                                80.1%        18790 patients
9     BLOOD: URINE (UA)                                     79.2%        19651 patients
10    INFLUENZA A                                           76.9%        21754 patients
11    INFLUENZA B                                           76.9%        21754 patients
12    PART. THROMBOPLASTIN TIME                             75.5%        23056 patients
13    PROTEIN: URINE (UA)                                   74.7%        23861 patients
14    POC:O2 SATURATION, ISTAT VENOUS                       74.5%        24087 patients
15    POC:HCO3 (V), ISTAT                                   74.4%        24101 patients
16    POC:TCO2 (V), ISTAT                                   74.4%        24101 patients
17    POC:BASE EXCESS, ISTAT                                74.4%        24173 patients
18    POC:LACTATE, ISTAT                                    74.3%        24188 patients
19    PCO2, Venous (Combined)                               74.3%        24278 patients
20    pH, Venous (Combined)                                 74.3%        24278 patients
21    LEUKOCYTE ESTERASE: URINE (UA)                        74.2%        24297 patients
22    PO2, Venous (Combined)                                74.2%        24298 patients
23    INR                                                   74.0%        24470 patients
24    PROTHROMBIN TIME                                      74.0%        24470 patients
25    TROPONIN I                                            71.1%        27237 patients
26    KETONE: URINE (UA)                                    70.4%        27914 patients
27    GLUCOSE: URINE (UA)                                   70.2%        28088 patients
28    NITRITE: URINE (UA)                                   66.7%        31364 patients
29    PH: URINE (UA)                                        66.6%        31518 patients
30    SPECIFIC GRAVITY: URINE (UA)                          66.6%        31532 patients
31    SARS-COV-2 RNA                                        35.0%        61279 patients
32    IMMATURE GRANULOCYTE % (AUTODIFF) WAM                 26.4%        69361 patients
33    IMMATURE GRANULOCYTE, ABSOLUTE (AUTO DIFF) WAM        26.4%        69361 patients
34    BASOPHIL % (AUTO DIFF)                                26.4%        69426 patients
35    EOSINOPHIL % (AUTO DIFF)                              26.4%        69426 patients
36    LYMPHOCYTE % (AUTO DIFF)                              26.4%        69426 patients
37    MONOCYTE % (AUTO DIFF)                                26.4%        69426 patients
38    NEUTROPHIL % (AUTO DIFF)                              26.4%        69426 patients
39    NEUTROPHIL, ABSOLUTE (AUTO DIFF)                      26.4%        69426 patients
40    NRBC (Combined)                                       25.1%        70638 patients
41    Basophil Absolute (Combined)                          24.8%        70887 patients
42    Eosinophil Absolute (Combined)                        23.8%        71832 patients
43    Monocyte Absolute (Combined)                          21.7%        73871 patients
44    Lymphocyte Absolute (Combined)                        21.5%        74027 patients
45    GLOBULIN                                              21.1%        74432 patients
46    ALT (SGPT)                                            21.0%        74468 patients
47    AST (SGOT)                                            21.0%        74476 patients
48    PROTEIN, TOTAL                                        21.0%        74481 patients
49    ALKALINE PHOSPHATASE                                  21.0%        74483 patients
50    BILIRUBIN, TOTAL                                      21.0%        74485 patients
51    ALBUMIN                                               21.0%        74487 patients
52    eGFR (Combined)                                       20.6%        74826 patients
53    ANION GAP                                             20.1%        75379 patients
54    CHLORIDE                                              20.0%        75390 patients
55    CO2                                                   20.0%        75390 patients
56    CREATININE                                            20.0%        75394 patients
57    Calcium (Combined)                                    20.0%        75417 patients
58    GLUCOSE                                               20.0%        75458 patients
59    BLOOD UREA NITROGEN (BUN)                             20.0%        75459 patients
60    Potassium (Combined)                                  20.0%        75474 patients
61    Sodium (Combined)                                     19.9%        75538 patients
62    RED CELL DISTRIBUTION WIDTH (RDW)                     19.4%        75971 patients
63    MEAN CORPUSCULAR VOLUME (MCV)                         19.4%        76030 patients
64    RED BLOOD CELLS (RBC)                                 19.3%        76043 patients
65    PLATELET COUNT (PLT)                                  19.3%        76061 patients
66    HEMATOCRIT (HCT)                                      19.3%        76089 patients
67    WHITE BLOOD CELLS (WBC)                               19.3%        76115 patients
68    HCT & Hemoglobin (Combined)                           19.2%        76137 patients

=== Summary Statistics ===
Total lab columns analyzed: 68
Training dataset size: 94286
90-95% missing: 1 columns
80-90% missing: 7 columns
50-80% missing: 22 columns
0-50% missing: 38 columns